# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 13:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ami_info', '0002_auto_20170818_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('creation_cate', models.DateTimeField(default=datetime.datetime(2017, 8, 23, 13, 51, 54, 896212, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='ami',
            name='number_updates',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ami',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 13, 51, 54, 888866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ami',
            name='end_of_life_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 13, 51, 54, 888901, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='update',
            name='ami',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ami_info.Ami'),
        ),
    ]
