# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ami_info', '0003_auto_20170823_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ami',
            name='number_updates',
        ),
        migrations.AlterField(
            model_name='ami',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 25, 882267, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ami',
            name='end_of_life_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 14, 41, 25, 882304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='update',
            name='creation_cate',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 14, 41, 25, 889401, tzinfo=utc)),
        ),
    ]
