# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ami_info', '0004_auto_20170823_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='creation_cate',
        ),
        migrations.AddField(
            model_name='update',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 15, 35, 18, 85230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ami',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 15, 35, 18, 77459, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ami',
            name='end_of_life_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 15, 35, 18, 77500, tzinfo=utc)),
        ),
    ]
