# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ami_info', '0005_auto_20170823_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ami',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 6, 53, 968600, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ami',
            name='end_of_life_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 16, 6, 53, 968633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='update',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 23, 16, 6, 53, 975925, tzinfo=utc)),
        ),
    ]
